name: test-run
target: modules.train_lcm.setup

trainer:
  model_path: ../stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors
  batch_size: 2
  seed: 65535
  wandb_id: "train_lcm"
  use_xformers: true
  accumulate_grad_batches: 2
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 1
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 10
  max_steps: -1

advanced:
  vae_encode_batch_size: -1 # same as batch_size
  train_text_encoder_1: true
  train_text_encoder_2: true
  text_encoder_1_lr: 1e-6
  text_encoder_2_lr: 1e-6
  v_parameterization: false

lightning:
  accelerator: gpu
  devices: -1
  precision: 16-mixed

dataset:
  name: data.bucket.AspectRatioDataset
  target_area: 262_144 # 1024*1024
  min_size: 512
  max_size: 512
  img_path: ../font2png/exports
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.PagedLion8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_cosine_with_hard_restarts_schedule_with_warmup
  params:
    num_warmup_steps: 394
    num_training_steps: 3948
    num_cycles: 2
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  seed: 65535
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  prompts:
    - "9, u000039, M+1"
