name: test-run
target: modules.train_sdxl_original.setup

denoiser:
  target: models.sgm.denoiser.Denoiser
  params:
    scaling: models.sgm.denoiser_scaling.VScalingWithEDMcNoise
  weighting: models.sgm.denoiser_weighting.VWeighting
  sigma_sampler: models.sgm.sigma_sampling.EDMSampling

trainer:
  model_path: ../cosxl.safetensors
  batch_size: 4
  seed: 1138
  wandb_id: "testtest"
  use_xformers: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 1
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 10
  max_steps: -1

advanced:
  vae_encode_batch_size: -1 # same as batch_size
  train_text_encoder_1: false
  train_text_encoder_2: false
  text_encoder_1_lr: 3e-6
  text_encoder_2_lr: 3e-6
  offset_noise: false
  offset_noise_val: 0.0375
  
lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed

dataset:
  name: data.bucket.AspectRatioDataset 
  # target_area: 1_048_576
  # min_size: 512
  # max_size: 2048
  img_path: "/root/niji-anime-latents"
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 0
    last_epoch: -1

sampling:
  enabled: false
  # unsupported 
  # scheduler: diffusers.EulerDiscreteScheduler
  # scheduler_params: {}
  #   beta_end: 0.012
  #   beta_schedule: scaled_linear
  #   beta_start: 0.00085
  #   num_train_timesteps: 1000
  #   interpolation_type: linear
  #   prediction_type: v_prediction
  #   steps_offset: 1
  #   timestep_spacing: leading
  #   timestep_type: continuous
  #   use_karras_sigmas: true
  # use_wandb: true
  # seed: 1234
  # height: 1280
  # width: 768
  every_n_steps: 1
  every_n_epochs: 1
  save_dir: "samples"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
