name: test-run
target: modules.train_lycoris.setup

trainer:
  model_path: ../sdxl-fonts-v1/checkpoint-5.safetensors
  batch_size: 32
  seed: 65535
  wandb_id: "train_lycoris"
  use_xformers: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0.1

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 2
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 20
  max_steps: -1

lycoris:
  linear_dim: 16
  linear_alpha: 8
  algo: locon
  factor: 4
  # preset: full
  multiplier: 1.0

advanced:
  vae_encode_batch_size: -1 # same as batch_size
  train_text_encoder_1: true
  train_text_encoder_2: true
  text_encoder_1_lr: 5e-5
  text_encoder_2_lr: 5e-5
  offset_noise: true
  offset_noise_val: 0.1
  min_snr: true
  min_snr_val: 1
  timestep_start: 0
  timestep_end: 1000
  v_parameterization: false
  zero_terminal_snr: false

lightning:
  accelerator: gpu
  devices: -1
  precision: 16-mixed

dataset:
  name: data.bucket.AspectRatioDataset
  target_area: 262_144 # 1024*1024
  min_size: 512
  max_size: 512
  img_path: ../styles
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.PagedLion8bit
  params:
    lr: 1e-4
    weight_decay: 0

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 0
    last_epoch: -1

sampling:
  enabled: false
  use_wandb: true
  seed: 65535
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  prompts:
    - "u000039, 9"
